### ISSUE TITLE
Can't open ros2 related files in picas-galactic branch

### ISSUE THREAD

**Issue by ver033** [rtenlab/ros2-picas#5]
@noaa99 
The reason may be that there are some .git hidden files in the ROS2 folder, and github regards it as a subsystem module. Could you please fix this problem?

**Comment by noaa99** [comment]
Thank you for letting me know that. I've updated `picas-galactic` version. Hope this will work.

**Comment by ver033** [comment]
@noaa99 
Thank you for promptly handling the matter. But maybe there is something wrong with my description. I want to say is that all the files of ROS 2 galactic can't be opened, not just the ROS 2 folder.

**Comment by noaa99** [comment]
@bopeng-saitama Can you try to clone `picas-galactic` branch, again? I uploaded all other folders.

**Comment by ver033** [comment]
Thank you for resolving this issue, now I can access all the files.
